### ISSUE TITLE
[Test] Write Test Cases for POST and DELETE Comments

### ISSUE THREAD

**Issue by piouson** [microapidev/comment-microapi#61]
### Is your feature request related to a problem? Please describe.
Tests for continuous integration

### Describe the solution you'd like

- [x] `POST /comments` #77 
- [x] `POST /comments/{commentId}/replies` #77 
- [x] `DELETE /comments/{commentId}` #77 
- [x] `DELETE /comments/{commentId}/replies/{replyId}` #77 

### Describe alternatives you've considered

<details>
  <summary>Tests not included</summary>

- [x] `GET /comments` #47 
- [x] `GET /comments/refs/{refId}` #47 
- [x] `GET /comments/{commentId}/replies` #47 
- [ ] `PATCH /comments/{commentId}`
- [ ] `PATCH /comments/{commentId}/votes`
- [ ] `PATCH /comments/{commentId}/votes`
- [ ] `PATCH /comments/{commentId}/flag`
- [ ] `PATCH /comments/{commentId}/replies/{replyId}`
- [ ] `PATCH /comments/{commentId}/replies/{replyId}/votes`
- [ ] `PATCH /comments/{commentId}/replies/{replyId}/flag`

</details>

### Additional context
Please assign me to this issue
