### ISSUE TITLE
[FEATURE REQUEST] Switch to jest-mongodb for test database and refactor database code

### ISSUE THREAD

**Issue by piouson** [microapidev/comment-microapi#73]
### Is your feature request related to a problem? Please describe.
[@shelf/jest-mongodb](https://jestjs.io/docs/en/mongodb) includes setup, teardown and database in-memory management

> Should resolve this nagging warning
>
> ![image](https://user-images.githubusercontent.com/17856665/85923682-23435d80-b885-11ea-85bb-0610b99036f3.png)

### Describe the solution you'd like
- [x] Add [@shelf/jest-mongodb](https://jestjs.io/docs/en/mongodb) package #77 
- [x] Refactor database code to switch between testing and production environments #77 
- [x] Drop wait timeouts from existing tests #77 

### Describe alternatives you've considered
- Using real cloud database for testing as in `TEST_DB_URL` from `.env.example`

### Additional context

**Comment by oscar-ekeyekwu** [comment]
Check issue #67 @dave-ok is doing something similar..

**Comment by piouson** [comment]
@oscar-ekeyekwu thanks, @dave-ok has done other bits and left the rest to me.
I just need to migrate to `jest-mongodb` and make sure all existing tests pass..
